-- PRODUCENCI
INSERT INTO PRODUCENT
VALUES (1, 'Solaris');

INSERT INTO PRODUCENT
VALUES (2, 'Moderus');

-- MIASTA
INSERT INTO MIASTO
VALUES('Poznań', 'miasto', 540365, 261.8);


INSERT INTO MIASTO
VALUES('Rokietnica', 'wieś', 7523, 6.8);


INSERT INTO MIASTO
VALUES('Swarzędz', 'wieś', 30739, 9);

-- STREFY
INSERT INTO STREFA
VALUES('A');

INSERT INTO STREFA
VALUES('ABC');

INSERT INTO STREFA
VALUES('B');

INSERT INTO STREFA
VALUES('C');