-- SEQUENCES
CREATE SEQUENCE producer_seq START 1;
CREATE SEQUENCE pojazd_seq START 1;
CREATE SEQUENCE przystanek_seq START 1;
CREATE SEQUENCE kasa_seq START 1;
CREATE SEQUENCE bilet_seq START 1;
CREATE SEQUENCE biletomat_seq START 1;
CREATE SEQUENCE model_seq START 1;